spring.application.name=sertissage
spring.datasource.url=jdbc:postgresql://localhost:5432/sertissage
spring.datasource.username=sertissage_admin
spring.datasource.password=Serti@ssage4738

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true